// Generated by `wrangler types` — placeholder until first deploy
interface CloudflareEnv {
  VIEWS: KVNamespace
  MEDIA: R2Bucket
  RESEND: SendEmail
  TURNSTILE_SITE_KEY: string
  RESEND_API_KEY: string
  TURNSTILE_SECRET: string
}
